/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef OHOS_DP_IPC_INTERFACE_CODE_H
#define OHOS_DP_IPC_INTERFACE_CODE_H

#include <cstdint>

/* SAID: 6001 */
namespace OHOS {
namespace DistributedDeviceProfile {
enum class DpIpcInterfaceCode : uint32_t {
    MIN = 0,
    PUT_ACL_PROFILE = 7, // new ipc code
    UPDATE_ACL_PROFILE = 8,
    GET_TRUST_DEVICE_PROFILE = 9,
    GET_ALL_TRUST_DEVICE_PROFILE = 10,
    GET_ACL_PROFILE = 11,
    GET_ALL_ACL_PROFILE = 12,
    DELETE_ACL_PROFILE = 13,
    PUT_SERVICE_PROFILE = 14,
    PUT_SERVICE_PROFILE_BATCH = 15,
    PUT_CHAR_PROFILE = 16,
    PUT_CHAR_PROFILE_BATCH = 17,
    GET_DEVICE_PROFILE_NEW = 18,
    GET_SERVICE_PROFILE = 19,
    GET_CHAR_PROFILE = 20,
    DEL_SERVICE_PROFILE = 21,
    DEL_CHAR_PROFILE = 22,
    SUBSCRIBE_DEVICE_PROFILE = 23,
    UNSUBSCRIBE_DEVICE_PROFILE = 24,
    SYNC_DEVICE_PROFILE_NEW = 25,
    SEND_SUBSCRIBE_INFOS = 26,
    ON_SYNC_COMPLETED = 27,
    ON_TRUST_DEVICE_PROFILE_ADD = 28,
    ON_TRUST_DEVICE_PROFILE_UPDATE = 29,
    ON_TRUST_DEVICE_PROFILE_DELETE = 30,
    ON_DEVICE_PROFILE_ADD = 31,
    ON_DEVICE_PROFILE_UPDATE = 32,
    ON_DEVICE_PROFILE_DELETE = 33,
    ON_SERVICE_PROFILE_ADD = 34,
    ON_SERVICE_PROFILE_UPDATE = 35,
    ON_SERVICE_PROFILE_DELETE = 36,
    ON_CHAR_PROFILE_ADD = 37,
    ON_CHAR_PROFILE_UPDATE = 38,
    ON_CHAR_PROFILE_DELETE = 39,
    ON_DEVICE_PROFILE_INITED = 40,
    SUBSCRIBE_DEVICE_PROFILE_INITED = 41,
    UNSUBSCRIBE_DEVICE_PROFILE_INITED = 42,
    ON_TRUST_DEVICE_PROFILE_ACTIVE = 43,
    ON_TRUST_DEVICE_PROFILE_INACTIVE = 44,
    PUT_ALL_TRUSTED_DEVICES = 45,
    PUT_DEVICE_PROFILE_BATCH = 46,
    GET_DEVICE_PROFILES = 47,
    GET_DEVICE_ICON_INFOS = 48,
    PUT_DEVICE_ICON_INFO_BATCH = 49,
    PUT_PRODUCT_INFO_BATCH = 50,
    DELETE_DEVICE_PROFILE_BATCH = 51,
    PUT_SERVICE_INFO_PROFILE = 52,
    DELETE_SERVICE_INFO_PROFILE = 53,
    UPDATE_SERVICE_INFO_PROFILE = 54,
    GET_SERVICE_INFO_PROFILE_BY_UNIQUE_KEY = 55,
    GET_SERVICE_INFO_PROFILE_LIST_BY_TOKEN_ID = 56,
    GET_ALL_SERVICE_INFO_PROFILE_LIST = 57,
    GET_SERVICE_INFO_PROFILE_LIST_BY_BUNDLE_NAME = 58,
    PUT_SESSION_KEY = 59,
    GET_SESSION_KEY = 60,
    UPDATE_SESSION_KEY = 61,
    DELETE_SESSION_KEY = 62,
    ON_PINCODE_INVALID = 63,
    SUBSCRIBE_PINCODE_INVALID = 64,
    UNSUBSCRIBE_PINCODE_INVALID = 65,
    PUT_LOCAL_SERVICE_INFO = 66,
    UPDATE_LOCAL_SERVICE_INFO = 67,
    GET_LOCAL_SERVICE_INFO_BY_BINDLE_AND_PINTYPE = 68,
    DELETE_LOCAL_SERVICE_INFO = 69,
    GET_ALL_ACL_INCLUDE_LNN_ACL = 70,
    ON_BUSINESS_EVENT = 71,
    REGISTER_BUSINESS_CALLBACK = 72,
    UNREGISTER_BUSINESS_CALLBACK = 73,
    PUT_BUSINESS_EVENT = 74,
    GET_BUSINESS_EVENT = 75,
    SYNC_STATIC_PROFILE = 76,
    GET_SERVICE_INFO_PROFILE_BY_SERVICE_ID = 77,
    GET_SERVICE_INFO_PROFILE_BY_TOKEN_ID = 78,
    GET_SERVICE_INFO_PROFILE_BY_REG_SER_ID = 79,
    MAX = 80
};
} // namespace DistributedDeviceProfile
} // namespace OHOS
#endif // OHOS_DP_IPC_INTERFACE_CODE_H
